### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jasonwynn10** [jasonwynn10/MurderMysteryPMMP#2]
- [ ] Customizable configuration on the following:
   - [ ] Gold spawn positions
   - [ ] Player spawn positions
   - [ ] Player armour and weapons
   - [ ] Gold count to give player the single shot bow
   - [ ] Time between gold spawns
   - [ ] Default equipment of players is as follows:
     * Traitor: Iron sword
     * Detective: Infinity Bow
     * Innocent: no items
 - [ ] Maximum of 7 players per game
 - [ ] Each player has one heart
 - [ ] Players do not lose hunger while playing
 - [ ] Multiple matches can be played at the same time in the same or different worlds
 - [ ] Players leave corps when they die
 - [ ] Throwing knifes
 - [ ] Compass showing nearest player

**Comment by PluginBOXone** [comment]
Can I make a German Config + Messages file? (Can I be the translater?) Would be nice ;)

**Comment by jasonwynn10** [comment]
sure after I make the english language file
